baseURL = "https://abhigenva.github.io/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Genva"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Skill"
url = "#skill"
weight = 5
[[menu.main]]
name = "Testimonial"
url = "#testimonial"
weight = 6
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 7
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "#about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "Genva, Inc. © 2023"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "https://formspree.io/f/mdoyoopv"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Mansarovar, Jaipur, Rajasthan, India"
email = "abhi.genva@gmail.com"
openingHours = "Open from 10am to 7pm (closes at 5pm Sunday)"
phone = "+(91) 998 709 4775"

[params.map]
APIkey = "AIzaSyDrgqikLIWjEVFAt2HUPsd7yxOPp4aRQ0E"
latitude = "26.854167"
longitude = "75.766630"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook"
url = "https://www.facebook.com/AbhiGenva"
weight = 1
[[params.social]]
icon = "fa-linkedin"
url = "https://www.linkedin.com/company/genva-inc/"
weight = 2
[[params.social]]
icon = "fa-github"
url = "https://github.com/Genva-Inc"
weight = 3
[[params.social]]
icon = "fa-medium"
url = "https://medium.com/@abhi.genva"
weight = 4
[[params.social]]
icon = "fa-youtube"
url = "https://www.youtube.com/channel/UCk5EMxJwT0mVRwn_jgvCj5A"
weight = 5
[[params.social]]
icon = "fa-twitter"
url = "https://twitter.com/AbhishekGenva"
weight = 6
[[params.social]]
icon = "fa-whatsapp"
url = "https://wa.me/8824137574/"
weight = 7
